parameters:
    app.api_version: 'v1'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/Kernel.php'
            - '../src/Entity/'
            - '../src/Dto/'
            - '../src/Exception/'

    App\EventSubscriber\ApiExceptionSubscriber:
        arguments:
            $debug: '%kernel.debug%'
            $apiPathPrefix: '/%app.api_version%/api'
